name: magie-alerts
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - numpy=2.3.5
  - pandas=2.3.3
  - scipy=1.16.2
  - matplotlib=3.10.6
  - tqdm=4.67.1
  - pytables=3.10.2
  - tomli=2.0.1
  - joblib=1.2.0
  - requests=2.31.0
  - notebook=7.5.0

  # testing
  - pytest=8.3.3

  - pip:
      - --no-deps
      - -e .
      - mastodon>=2.2.1
      - geomagpy @ git+https://github.com/geomagpy/magpy.git@c10bfb3a8d03587de4b80ff70d821c4e19aa5066
