name: magie
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - numpy=1.26.4
  - pandas=2.3.3
  - scipy=1.16.2
  - matplotlib=3.10.6
  - tqdm=4.67.1
  - pytables=3.10.2
  - tomli=2.0.1
  - joblib=1.2.0
  - requests=2.31.0
  - notebook=7.5.0
  - python-dotenv=1.2.2
  
  # testing
  - pytest=8.3.3

  - pip:
      - geomagpy @ git+https://github.com/geomagpy/magpy.git@c10bfb3a8d03587de4b80ff70d821c4e19aa5066
